import { Button, StandardButton, VerticalBox, HorizontalBox, GridBox } from "std-widgets.slint";
import { Globals } from "globals.slint";
export component EnglishApp {
    VerticalLayout {
        HorizontalLayout {
            padding-left: 30px;
            padding-right: 30px;
            padding-top: 10px;
            height: 40px;
            width: 100%;
            alignment: space-between;
            Rectangle {
                clip: true;
                TouchArea {
                    HorizontalBox {
                        alignment: center;
                        padding: 0px;
                        Image {
                            colorize: Globals.themeStatus;
                            vertical-alignment: center;
                            source: @image-url("assets/night-mode.png");
                        }

                        Text {
                            vertical-alignment: center;
                            horizontal-alignment: right;
                            text: "Dark Mode";
                            font-family: "Vazirmatn";
                            font-weight: 900;
                            font-size: 16px;

                            color: Globals.themeStatus;
                        }
                    }

                    clicked => {
                    }
                }
            }

            Rectangle { }

            TouchArea {
                clicked => {
                    Globals.close();
                }
                Image {
                    image-fit: contain;
                    source: @image-url("assets/close.png");
                }
            }
        }

        HorizontalLayout {
            height: 275px;
            alignment: center;
            VerticalBox {
                HorizontalBox {
                    alignment: center;
                    Image {
                        image-fit: fill;
                        width: 256px;
                        height: 256px;
                        source: @image-url("assets/logo.png");
                    }
                }
            }
        }
        VerticalLayout {
            HorizontalBox {
                alignment: center;
                Image {
                    source: @image-url("assets/xerotext.png");
                    width: 512px;
                    height: 100px;
                }
            }

            HorizontalBox {
                height: 50px;
                Text {
                    color: Globals.themeStatus;
                    horizontal-alignment: center;
                    text: "Your Support Would Be Highly Appreciated!";
                    font-size: 20px;
                    font-family: "Vazirmatn";
                    font-weight: 900;
                }
            }

            HorizontalBox {
                height: 50px;
                alignment: center;
                GridBox {
                    spacing: 30px;
                    TouchArea {
                        Image {
                            colorize: Globals.themeStatus;
                            width: 30px;
                            height: 30px;
                            source: @image-url("assets/github.png");
                        }

                        clicked => {
                            Globals.openUrl("https://github.com/xerolinuxdev");
                        }
                    }

                    TouchArea {
                        Image {

                            colorize: Globals.themeStatus;
                            width: 30px;
                            height: 30px;
                            source: @image-url("assets/twitter.png");
                        }

                        clicked => {
                            Globals.openUrl("https://x.com/XeroLinuxOP");
                        }
                    }


                    TouchArea {
                        Image {

                            colorize: Globals.themeStatus;
                            width: 30px;
                            height: 30px;
                            source: @image-url("assets/discord.png");
                        }

                        clicked => {
                            Globals.openUrl("https://discord.gg/5sqxTSuKZu");
                        }
                    }

                    TouchArea {
                        Image {

                            colorize: Globals.themeStatus;
                            width: 30px;
                            height: 30px;
                            source: @image-url("assets/mastadon.png");
                        }

                        clicked => {
                            Globals.openUrl("https://fosstodon.org/@XeroLinux");
                        }
                    }

                    TouchArea {
                        Image {

                            colorize: Globals.themeStatus;
                            width: 30px;
                            height: 30px;
                            source: @image-url("assets/coffee-cup.png");
                        }

                        clicked => {
                            Globals.openUrl("https://ko-fi.com/XeroLinux");
                        }
                    }

                    TouchArea {
                        Image {
                            colorize: Globals.themeStatus;
                            width: 30px;
                            height: 30px;
                            source: @image-url("assets/web.png");
                        }

                        clicked => {
                            Globals.openUrl("https://xerolinux.xyz");
                        }
                    }

                    TouchArea {
                        Image {
                            colorize: Globals.themeStatus;
                            width: 30px;
                            height: 30px;
                            source: @image-url("assets/open-book.png");
                        }

                        clicked => {
                            Globals.openUrl("https:/wiki.xerolinux.xyz");
                        }
                    }
                }
            }

            VerticalBox {
                alignment: start;
                height: 40px;
                Text {

                    color: Globals.themeStatus;
                    height: 25px;
                    text: "Hit the button below to install XeroLinux on your computer";
                    font-size: 16px;
                    font-family: "Vazirmatn";
                    horizontal-alignment: center;
                    vertical-alignment: center;
                }
            }

            HorizontalLayout {
                alignment: center;
                TouchArea {
                    clicked => {
                        Globals.startInstaller();
                    }
                    Rectangle {
                        width: 170px;
                        height: 42px;
                        background: Globals.currentTheme ? white : Globals.textDark;
                        animate background, drop-shadow-color, drop-shadow-blur {
                            duration: 275ms;
                            easing: ease-in-out;
                        }
                        border-radius: 8px;
                        drop-shadow-color: Globals.currentTheme ? #404040 : #404040;
                        drop-shadow-blur: 12px;
                        drop-shadow-offset-x: 2px;
                        drop-shadow-offset-y: 2px;
                        HorizontalBox {
                            alignment: center;

                            Image {
                                //colorize: Globals.currentTheme ? transparent : white;
                                image-fit: fill;
                                source: @image-url("assets/inbox.png");
                            }

                            Text {
                                text: "Launch Installer";
                                font-family: "Vazirmatn";
                                //color: Globals.primaryDark
                                font-size: 14px;
                                font-weight: 750;
                            }
                        }
                    }
                }
            }

            HorizontalLayout {
                alignment: start;
                TouchArea {
                    clicked => {
                    }
                    HorizontalBox {
                        padding-left: 30px;
                        Image {
                            colorize: Globals.themeStatus;
                            vertical-alignment: center;
                            source: @image-url("assets/lang.png");
                        }

                        Text {
                            vertical-alignment: center;
                            horizontal-alignment: right;
                            text: "This tool was originally developed by the Parch Linux Team";
                            font-family: "Vazirmatn";
                            font-weight: 900;
                            font-size: 10px;
                            color: Globals.themeStatus;
                        }
                    }
                }
            }
        }
    }
}
